# Generated by Django 5.2.8 on 2025-12-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_room_image1_room_image2_room_image3_room_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
    ]
