# Generated by Django 5.2.8 on 2025-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_homepage_hero_image_alter_homepage_room1_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='room1_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='room2_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='room3_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
